/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 scene.gltf
Author: katjagricishina (https://sketchfab.com/katjagricishina)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sofa-03550a3529c24611a12aa158747374e0
Title: Sofa
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function SofaBlack(props) {
  const { nodes, materials } = useGLTF('../../../public/models/sofaBlack/scene.gltf')
  const sofaBlackRef = useRef();
  
  useFrame(() => {
    sofaBlackRef.current.rotation.y += 0.01; 
  });
  return (
    <group ref={sofaBlackRef} {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('../../../public/models/sofaBlack/scene.gltf')
