/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 scene.gltf
Author: shedmon (https://sketchfab.com/shedmon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-table-acd1cef307b94803846d624b251a4e63
Title: Wooden Table
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export function Table(props) {
  const { nodes, materials } = useGLTF('../../../public/models/table/scene.gltf');
  const tableRef = useRef();

  useFrame(() => {
    tableRef.current.rotation.y += 0.01;
  });

  return (
    <group ref={tableRef} {...props} dispose={null} receiveShadow castShadow>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.036}>
        <mesh
          geometry={nodes.defaultMaterial.geometry}
          material={materials.Default}
          rotation={[Math.PI / 2, 0, 0]}
          receiveShadow
          castShadow 
          
        />
      </group>
    </group>
  );
}

useGLTF.preload('../../../public/models/table/scene.gltf');
