/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 scene.gltf
Author: Kuutti Siitonen (https://sketchfab.com/kuuttisiitonen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/monobloc-plastic-garden-chair-68089dce5fa1461981d690f1cfd657fa
Title: Monobloc Plastic Garden Chair
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function ChairWhite(props) {
  const { nodes, materials } = useGLTF('../../../public/models/chairWhite/scene.gltf');
  const chairWhiteRef = useRef();

  useFrame(() => {
    chairWhiteRef.current.rotation.y += 0.01; 
  });

  return (
    <group {...props}  ref={chairWhiteRef} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Monobloc_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('../../../public/models/chairWhite/scene.gltf')
