/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 scene.gltf
Author: shedmon (https://sketchfab.com/shedmon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-table-acd1cef307b94803846d624b251a4e63
Title: Wooden Table
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { Group, Material } from 'three';

interface TablePops {
  [key: string]: any;
}

export const Table: React.FC<TablePops> = (props) => {
  const { nodes, materials } = useGLTF('../../../public/models/table/scene.gltf') as unknown as {
    nodes: { [key: string]: Group };
    materials: { [key: string]: Material };
  };
  const tableRef = useRef<Group>(null);

  useFrame(() => {
    if (tableRef.current) {
      tableRef.current.rotation.y += 0.01;
    }
  });

  return (
    <group ref={tableRef} {...props} dispose={null} receiveShadow castShadow>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.036}>
        <mesh
          geometry={(nodes.defaultMaterial as unknown as THREE.Mesh).geometry}
          material={materials.Default}
          rotation={[Math.PI / 2, 0, 0]}
          receiveShadow
          castShadow 
          
        />
      </group>
    </group>
  );
}

useGLTF.preload('../../../public/models/table/scene.gltf');
